### ISSUE TITLE
v.0.4.0 can't handle multiple-word queries

### ISSUE THREAD

**Issue by Jyqft** [tupton/alfred-chrome-history#14]
It seems that entering a query that has the space character in it in v.0.4.0 causes the fallback search engines to display. The previous version did not have this issue.

I couldn't find any errors in the debugger's log.

I'm on Alfred 2 v2.8.1 (425) on Mac OS X 10.10.5 (14F1509).

**Comment by tupton** [comment]
I believe the escaping rules somehow got changed; #18 fixes this I believe, as it no longer escapes spaces in the passed query.
